# Generated by Django 4.1.7 on 2023-03-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='content',
            new_name='blog',
        ),
    ]
